DROP TABLE IF EXISTS LondonStopAndSearch;
DROP TABLE IF EXISTS LondonOutcomes;
DROP TABLE IF EXISTS LondonStreet;
DROP TABLE IF EXISTS NYPDComplaints;
DROP TABLE IF EXISTS ChicagoCrimes;
DROP TABLE IF EXISTS LACrimes;
